### PR TITLE
Improve content of PyPI tarball

### PR DESCRIPTION
**Pull request by ghisvail**
This commit adds the change log and test suite to the tarball produced by `sdist`, which is recommended for Linux packaging downstream. Please consider merging this proposal, followed by an upload of a new release to PyPI.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Thanks! I'm quite busy at the moment (because of exams coming up) and I'd like to take a closer look at what this changes first - so it's probably going to take 4-6 weeks until I get to it. Hope that's okay :wink:

**Comment by ghisvail** [comment]
Take your time. Good luck with the exams.

**Comment by The-Compiler** [comment]
Sorry, I completely forgot about this! However, I don't see any change in how the source archives look:

```
$ als dist/pytest-xvfb-1.0.0.tar.gz
drwxr-xr-x florian/florian   0 2017-12-04 10:42 pytest-xvfb-1.0.0/
-rw-r--r-- florian/florian  51 2017-12-04 10:42 pytest-xvfb-1.0.0/MANIFEST.in
-rw-r--r-- florian/florian 421 2017-02-19 22:23 pytest-xvfb-1.0.0/.travis.yml
-rw-r--r-- florian/florian  38 2017-12-04 10:42 pytest-xvfb-1.0.0/setup.cfg
drwxr-xr-x florian/florian   0 2017-12-04 10:42 pytest-xvfb-1.0.0/tests/
-rw-r--r-- florian/florian 6076 2017-12-04 10:41 pytest-xvfb-1.0.0/tests/test_xvfb.py
-rw-r--r-- florian/florian   28 2017-02-19 22:23 pytest-xvfb-1.0.0/tests/conftest.py
-rw-r--r-- florian/florian  270 2017-02-19 22:23 pytest-xvfb-1.0.0/tests/test_xvfb_windows.py
-rw-r--r-- florian/florian  829 2017-12-04 10:41 pytest-xvfb-1.0.0/CHANGELOG.rst
-rw-r--r-- florian/florian   85 2017-02-19 22:23 pytest-xvfb-1.0.0/.gitignore
-rw-r--r-- florian/florian 5061 2017-12-04 10:42 pytest-xvfb-1.0.0/PKG-INFO
-rw-r--r-- florian/florian 3465 2017-12-04 10:41 pytest-xvfb-1.0.0/pytest_xvfb.py
-rw-r--r-- florian/florian  205 2017-02-19 22:23 pytest-xvfb-1.0.0/tox.ini
-rw-r--r-- florian/florian 1537 2017-02-19 22:23 pytest-xvfb-1.0.0/setup.py
-rw-r--r-- florian/florian  915 2017-02-19 22:23 pytest-xvfb-1.0.0/appveyor.yml
-rw-r--r-- florian/florian 3305 2017-02-19 22:23 pytest-xvfb-1.0.0/README.rst
-rw-r--r-- florian/florian   42 2017-02-19 22:23 pytest-xvfb-1.0.0/pytest.ini
drwxr-xr-x florian/florian    0 2017-12-04 10:42 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/
-rw-r--r-- florian/florian  399 2017-12-04 10:42 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/SOURCES.txt
-rw-r--r-- florian/florian 5061 2017-12-04 10:42 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/PKG-INFO
-rw-r--r-- florian/florian   31 2017-12-04 10:42 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/entry_points.txt
-rw-r--r-- florian/florian   12 2017-12-04 10:42 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/top_level.txt
-rw-r--r-- florian/florian    1 2017-12-04 10:42 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/dependency_links.txt
-rw-r--r-- florian/florian   38 2017-12-04 10:42 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/requires.txt
-rw-r--r-- florian/florian 1081 2017-02-19 22:23 pytest-xvfb-1.0.0/LICENSE
```

```
$ als dist/pytest-xvfb-1.0.0-nomanifest.tar.gz 
drwxr-xr-x florian/florian   0 2017-12-04 10:41 pytest-xvfb-1.0.0/
-rw-r--r-- florian/florian 421 2017-02-19 22:23 pytest-xvfb-1.0.0/.travis.yml
-rw-r--r-- florian/florian  38 2017-12-04 10:41 pytest-xvfb-1.0.0/setup.cfg
drwxr-xr-x florian/florian   0 2017-12-04 10:41 pytest-xvfb-1.0.0/tests/
-rw-r--r-- florian/florian 6076 2017-12-04 10:41 pytest-xvfb-1.0.0/tests/test_xvfb.py
-rw-r--r-- florian/florian   28 2017-02-19 22:23 pytest-xvfb-1.0.0/tests/conftest.py
-rw-r--r-- florian/florian  270 2017-02-19 22:23 pytest-xvfb-1.0.0/tests/test_xvfb_windows.py
-rw-r--r-- florian/florian  829 2017-12-04 10:41 pytest-xvfb-1.0.0/CHANGELOG.rst
-rw-r--r-- florian/florian   85 2017-02-19 22:23 pytest-xvfb-1.0.0/.gitignore
-rw-r--r-- florian/florian 5061 2017-12-04 10:41 pytest-xvfb-1.0.0/PKG-INFO
-rw-r--r-- florian/florian 3465 2017-12-04 10:41 pytest-xvfb-1.0.0/pytest_xvfb.py
-rw-r--r-- florian/florian  205 2017-02-19 22:23 pytest-xvfb-1.0.0/tox.ini
-rw-r--r-- florian/florian 1537 2017-02-19 22:23 pytest-xvfb-1.0.0/setup.py
-rw-r--r-- florian/florian  915 2017-02-19 22:23 pytest-xvfb-1.0.0/appveyor.yml
-rw-r--r-- florian/florian 3305 2017-02-19 22:23 pytest-xvfb-1.0.0/README.rst
-rw-r--r-- florian/florian   42 2017-02-19 22:23 pytest-xvfb-1.0.0/pytest.ini
drwxr-xr-x florian/florian    0 2017-12-04 10:41 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/
-rw-r--r-- florian/florian  387 2017-12-04 10:41 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/SOURCES.txt
-rw-r--r-- florian/florian 5061 2017-12-04 10:41 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/PKG-INFO
-rw-r--r-- florian/florian   31 2017-12-04 10:41 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/entry_points.txt
-rw-r--r-- florian/florian   12 2017-12-04 10:41 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/top_level.txt
-rw-r--r-- florian/florian    1 2017-12-04 10:41 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/dependency_links.txt
-rw-r--r-- florian/florian   38 2017-12-04 10:41 pytest-xvfb-1.0.0/pytest_xvfb.egg-info/requires.txt
-rw-r--r-- florian/florian 1081 2017-02-19 22:23 pytest-xvfb-1.0.0/LICENSE
```

But indeed the last release doesn't contain those files - maybe something changed in how `setuptools` packages things in the meantime?

**Comment by ghisvail** [comment]
> But indeed the last release doesn't contain those files - maybe something changed in how `setuptools` packages things in the meantime?

I don't think so. Based on the content of your `setup.py` and lack of a `MANIFEST.in` file, the usual rules apply, i.e. the source dist should contain `README.rst` + the modules registered in the setup object. So, you do need a `MANIFEST.in` to add the tests and change log files.

**Comment by The-Compiler** [comment]
Apparently not - see the output above. The `-nomanifest.tar.gz` was created without having a `MANIFEST.in`, and contains the same files.

**Comment by The-Compiler** [comment]
Well, if it doesn't help I guess it doesn't hurt, so I'm merging this now. Sorry for taking so long! I'll release a v1.1.0 now.

**Pull request merged**
